sudo: false
dist: trusty
language: ruby
rvm:
  - "2.4.0"
env:
  - DB=pgsql
services:
  - postgresql
addons:
  postgresql: "9.5"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database cappuccino_test;' -U postgres
bundler_args: --binstubs=./bundler_stubs
